name: provider_template
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.3.0+3

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.0

  dio: ^5.3.2
  dartz: ^0.10.1
  provider: ^6.0.5
  path_provider: ^2.1.0
  cupertino_icons: ^1.0.2
  internet_connection_checker: ^1.0.0+1

  flutter_localizations: # Eklenecek satır
    sdk: flutter # Eklenecek satır

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat_medium.ttf
        - asset: assets/fonts/montserrat_regular.ttf

